-- Week 4 Project - SQLite and Spatialite
-- This is a sql script to create geospatial tables in a SQLite database.
-- To execute run '.read CreateTables.sql' in sqlite 

-- This data inserted into the tables was generated by ChatGPT.
-- SRID 4326 used for everything (WGS84 GCS)

-- Drop the tables if they already exist
DROP TABLE IF EXISTS sample_points;
DROP TABLE IF EXISTS sample_lines;
DROP TABLE IF EXISTS sample_polygons;


--This is the SQL version to load the spatialite extension
SELECT load_extension('mod_spatialite'); -- If added to PATH or navigate to location
-- This must be loaded every time the database is opened

SELECT InitSpatialMetadata(1); 
--Initialize metadata (run once per database)


-- Geometry stored as BLOB (Binary Large Object)
-- Used WKT constructors (ST_GeomFromText). 

-- Create Table to hold point data with a geometry field (geom)
CREATE TABLE sample_points (
    id INTEGER PRIMARY KEY,
    name TEXT,
    category TEXT,
    value REAL,
    geom BLOB
);

-- Insert 10 points into table
INSERT INTO sample_points (id, name, category, value, geom) VALUES
(1, 'Sydney', 'City', 5078000,
 ST_GeomFromText('POINT(151.2093 -33.8688)', 4326)),

(2, 'Melbourne', 'City', 4936000,
 ST_GeomFromText('POINT(144.9631 -37.8136)', 4326)),

(3, 'Brisbane', 'City', 2560000,
 ST_GeomFromText('POINT(153.0251 -27.4698)', 4326)),

(4, 'Perth', 'City', 2059000,
 ST_GeomFromText('POINT(115.8605 -31.9505)', 4326)),

(5, 'Adelaide', 'City', 1400000,
 ST_GeomFromText('POINT(138.6007 -34.9285)', 4326)),

(6, 'Sensor A', 'Sensor', 12.5,
 ST_GeomFromText('POINT(151.30 -33.90)', 4326)),

(7, 'Sensor B', 'Sensor', 8.1,
 ST_GeomFromText('POINT(151.10 -33.70)', 4326)),

(8, 'Sensor C', 'Sensor', 15.3,
 ST_GeomFromText('POINT(144.90 -37.70)', 4326)),

(9, 'Station X', 'Station', 22.0,
 ST_GeomFromText('POINT(153.10 -27.50)', 4326)),

(10,'Station Y', 'Station', 19.4,
 ST_GeomFromText('POINT(138.70 -35.00)', 4326));



-- Create table to hold linestring data (geometry in 'geom' column)
CREATE TABLE sample_lines (
    id INTEGER PRIMARY KEY,
    name TEXT,
    type TEXT,
    length_km REAL,
    geom BLOB
);

-- Insert 8 linestrings
INSERT INTO sample_lines (id, name, type, value, geom) VALUES
(1, 'Route A', 'Road', 18.4,
 ST_GeomFromText(
   'LINESTRING(
      151.18 -33.86,
      151.22 -33.88,
      151.26 -33.91,
      151.30 -33.94
   )', 4326)),

(2, 'Route B', 'Road', 25.1,
 ST_GeomFromText(
   'LINESTRING(
      144.92 -37.79,
      144.96 -37.81,
      145.01 -37.84,
      145.07 -37.87
   )', 4326)),

(3, 'River X', 'River', 52.7,
 ST_GeomFromText(
   'LINESTRING(
      153.00 -27.43,
      153.03 -27.47,
      153.07 -27.51,
      153.10 -27.55,
      153.14 -27.59
   )', 4326)),

(4, 'Pipeline 1', 'Pipeline', 14.9,
 ST_GeomFromText(
   'LINESTRING(
      138.58 -34.88,
      138.60 -34.92,
      138.63 -34.96,
      138.67 -35.01
   )', 4326)),

(5, 'Rail Line', 'Rail', 36.3,
 ST_GeomFromText(
   'LINESTRING(
      115.84 -31.93,
      115.88 -31.97,
      115.92 -32.01,
      115.97 -32.06
   )', 4326)),

(6, 'Track Alpha', 'Trail', 9.2,
 ST_GeomFromText(
   'LINESTRING(
      151.08 -33.78,
      151.11 -33.81,
      151.14 -33.84
   )', 4326)),

(7, 'Track Beta', 'Trail', 11.5,
 ST_GeomFromText(
   'LINESTRING(
      144.88 -37.73,
      144.92 -37.75,
      144.96 -37.77,
      145.00 -37.79
   )', 4326)),

(8, 'Canal Z', 'Canal', 16.0,
 ST_GeomFromText(
   'LINESTRING(
      153.04 -27.46,
      153.06 -27.48,
      153.08 -27.50,
      153.10 -27.52,
      153.12 -27.54
   )', 4326));



-- Create table to hold polygon data
CREATE TABLE sample_polygons (
    id INTEGER PRIMARY KEY,
    name TEXT,
    zone_type TEXT,
    area_sqkm REAL,
    geom BLOB
);

-- Insert 6 polygons

INSERT INTO sample_polygons (id, name, zone_type, value, geom) VALUES
(1, 'Sydney Zone', 'Urban', 1200.5,
 ST_GeomFromText(
   'POLYGON((
      151.10 -33.80,
      151.30 -33.80,
      151.30 -34.00,
      151.10 -34.00,
      151.10 -33.80
   ))', 4326)),

(2, 'Melbourne Zone', 'Urban', 980.2,
 ST_GeomFromText(
   'POLYGON((
      144.85 -37.70,
      145.10 -37.70,
      145.10 -37.90,
      144.85 -37.90,
      144.85 -37.70
   ))', 4326)),

(3, 'Brisbane Zone', 'Urban', 760.9,
 ST_GeomFromText(
   'POLYGON((
      152.95 -27.40,
      153.15 -27.40,
      153.15 -27.60,
      152.95 -27.60,
      152.95 -27.40
   ))', 4326)),

(4, 'Protected Area A', 'Conservation', 3400.0,
 ST_GeomFromText(
   'POLYGON((
      138.50 -34.80,
      138.80 -34.80,
      138.80 -35.10,
      138.50 -35.10,
      138.50 -34.80
   ))', 4326)),

(5, 'Coastal Reserve', 'Conservation', 2100.7,
 ST_GeomFromText(
   'POLYGON((
      115.80 -31.90,
      116.00 -31.90,
      116.00 -32.10,
      115.80 -32.10,
      115.80 -31.90
   ))', 4326)),

(6, 'Industrial Zone', 'Industrial', 450.3,
 ST_GeomFromText(
   'POLYGON((
      151.20 -33.95,
      151.35 -33.95,
      151.35 -34.05,
      151.20 -34.05,
      151.20 -33.95
   ))', 4326));


-- Register the Spatial Data for 3 tables 
-- Run after the tables are created
SELECT RecoverGeometryColumn(
    'sample_points',
    'geom',
    4326,
    'POINT',
    'XY'
);

SELECT RecoverGeometryColumn(
    'sample_lines',
    'geom',
    4326,
    'LINESTRING',
    'XY'
);

SELECT RecoverGeometryColumn(
    'sample_polygons',
    'geom',
    4326,
    'POLYGON',
    'XY'
);
