-- This is a sql script to create some tables in my database (play.db)
-- Week 4 Day 1
-- This data was generated by ChatGPT using the following prompt:
/*
I would like to play around with some spatial queries on a database I'm creating in SQLite with SpatialLite. I want to create the tables and then insert data into the tables. Can you give me some generated sample data of 5 -20 points, 5-20 linestrings, 5 - 20 polygons with at least 3-4 columns of string and numerical values as well as the geometry value (using BLOB method)
*/

-- SRID 4326 used for everything (WGS 84 GCS)

.load mod_spatialite
.mode column
.headers on

--Create some points

--Create table to hold point data

CREATE TABLE sample_points (
    id INTEGER PRIMARY KEY,
    name TEXT,
    category TEXT,
    value REAL,
    geom BLOB
);

-- Insert 10 points

INSERT INTO sample_points VALUES
(1, 'Sydney', 'City', 5078000, MakePoint(151.2093, -33.8688, 4326)),
(2, 'Melbourne', 'City', 4936000, MakePoint(144.9631, -37.8136, 4326)),
(3, 'Brisbane', 'City', 2560000, MakePoint(153.0251, -27.4698, 4326)),
(4, 'Perth', 'City', 2059000, MakePoint(115.8605, -31.9505, 4326)),
(5, 'Adelaide', 'City', 1400000, MakePoint(138.6007, -34.9285, 4326)),
(6, 'Sensor A', 'Sensor', 12.5, MakePoint(151.3, -33.9, 4326)),
(7, 'Sensor B', 'Sensor', 8.1, MakePoint(151.1, -33.7, 4326)),
(8, 'Sensor C', 'Sensor', 15.3, MakePoint(144.9, -37.7, 4326)),
(9, 'Station X', 'Station', 22.0, MakePoint(153.1, -27.5, 4326)),
(10,'Station Y', 'Station', 19.4, MakePoint(138.7, -35.0, 4326));


--Create some Linestrings

CREATE TABLE sample_lines (
    id INTEGER PRIMARY KEY,
    name TEXT,
    type TEXT,
    length_km REAL,
    geom BLOB
);

-- Insert 8 Polylines

INSERT INTO sample_lines VALUES
(1, 'Route A', 'Road', 18.4,
 MakeLine(
    MakePoint(151.18, -33.86, 4326),
    MakePoint(151.22, -33.88, 4326),
    MakePoint(151.26, -33.91, 4326),
    MakePoint(151.30, -33.94, 4326)
 )),

(2, 'Route B', 'Road', 25.1,
 MakeLine(
    MakePoint(144.92, -37.79, 4326),
    MakePoint(144.96, -37.81, 4326),
    MakePoint(145.01, -37.84, 4326),
    MakePoint(145.07, -37.87, 4326)
 )),

(3, 'River X', 'River', 52.7,
 MakeLine(
    MakePoint(153.00, -27.43, 4326),
    MakePoint(153.03, -27.47, 4326),
    MakePoint(153.07, -27.51, 4326),
    MakePoint(153.10, -27.55, 4326),
    MakePoint(153.14, -27.59, 4326)
 )),

(4, 'Pipeline 1', 'Pipeline', 14.9,
 MakeLine(
    MakePoint(138.58, -34.88, 4326),
    MakePoint(138.60, -34.92, 4326),
    MakePoint(138.63, -34.96, 4326),
    MakePoint(138.67, -35.01, 4326)
 )),

(5, 'Rail Line', 'Rail', 36.3,
 MakeLine(
    MakePoint(115.84, -31.93, 4326),
    MakePoint(115.88, -31.97, 4326),
    MakePoint(115.92, -32.01, 4326),
    MakePoint(115.97, -32.06, 4326)
 )),

(6, 'Track Alpha', 'Trail', 9.2,
 MakeLine(
    MakePoint(151.08, -33.78, 4326),
    MakePoint(151.11, -33.81, 4326),
    MakePoint(151.14, -33.84, 4326)
 )),

(7, 'Track Beta', 'Trail', 11.5,
 MakeLine(
    MakePoint(144.88, -37.73, 4326),
    MakePoint(144.92, -37.75, 4326),
    MakePoint(144.96, -37.77, 4326),
    MakePoint(145.00, -37.79, 4326)
 )),

(8, 'Canal Z', 'Canal', 16.0,
 MakeLine(
    MakePoint(153.04, -27.46, 4326),
    MakePoint(153.06, -27.48, 4326),
    MakePoint(153.08, -27.50, 4326),
    MakePoint(153.10, -27.52, 4326),
    MakePoint(153.12, -27.54, 4326)
 ));

-- Create some polygons

CREATE TABLE sample_polygons (
    id INTEGER PRIMARY KEY,
    name TEXT,
    zone_type TEXT,
    area_sqkm REAL,
    geom BLOB
);

-- Insert 6 polygons

INSERT INTO sample_polygons VALUES
(1, 'Sydney Zone', 'Urban', 1200.5,
 MakePolygon(MakeLine(
    MakePoint(151.10, -33.80, 4326),
    MakePoint(151.30, -33.80, 4326),
    MakePoint(151.30, -34.00, 4326),
    MakePoint(151.10, -34.00, 4326),
    MakePoint(151.10, -33.80, 4326)
 ))),

(2, 'Melbourne Zone', 'Urban', 980.2,
 MakePolygon(MakeLine(
    MakePoint(144.85, -37.70, 4326),
    MakePoint(145.10, -37.70, 4326),
    MakePoint(145.10, -37.90, 4326),
    MakePoint(144.85, -37.90, 4326),
    MakePoint(144.85, -37.70, 4326)
 ))),

(3, 'Brisbane Zone', 'Urban', 760.9,
 MakePolygon(MakeLine(
    MakePoint(152.95, -27.40, 4326),
    MakePoint(153.15, -27.40, 4326),
    MakePoint(153.15, -27.60, 4326),
    MakePoint(152.95, -27.60, 4326),
    MakePoint(152.95, -27.40, 4326)
 ))),

(4, 'Protected Area A', 'Conservation', 3400.0,
 MakePolygon(MakeLine(
    MakePoint(138.50, -34.80, 4326),
    MakePoint(138.80, -34.80, 4326),
    MakePoint(138.80, -35.10, 4326),
    MakePoint(138.50, -35.10, 4326),
    MakePoint(138.50, -34.80, 4326)
 ))),

(5, 'Coastal Reserve', 'Conservation', 2100.7,
 MakePolygon(MakeLine(
    MakePoint(115.80, -31.90, 4326),
    MakePoint(116.00, -31.90, 4326),
    MakePoint(116.00, -32.10, 4326),
    MakePoint(115.80, -32.10, 4326),
    MakePoint(115.80, -31.90, 4326)
 ))),

(6, 'Industrial Zone', 'Industrial', 450.3,
 MakePolygon(MakeLine(
    MakePoint(151.20, -33.95, 4326),
    MakePoint(151.35, -33.95, 4326),
    MakePoint(151.35, -34.05, 4326),
    MakePoint(151.20, -34.05, 4326),
    MakePoint(151.20, -33.95, 4326)
 )));

--Register the Spatial Data for 3 tables
SELECT RecoverGeometryColumn(
    'sample_points',
    'geom',
    4326,
    'POINT',
    'XY'
);

SELECT RecoverGeometryColumn(
    'sample_lines',
    'geom',
    4326,
    'LINESTRING',
    'XY'
);

SELECT RecoverGeometryColumn(
    'sample_polygons',
    'geom',
    4326,
    'POLYGON',
    'XY'
);
